name: Build and Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      nodeVersion:
        description: "Version de nodejs"
        default: "21.6.2"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Install dependancies
        run: npm install --ignore-scripts

      - name: Build plugin
        run: npm run build

      - name: Get package version
        id: pkg-version
        run: echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: Create release
        id: create-release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ steps.pkg-version.outputs.version}}

      - name: Clean previous install
        run: rm -rf ./node_modules

      - name: Install production dependancies
        run: npm install --ignore-script --omit=dev

      - name: Compress build folder
        run: zip -r ./package.zip ./package.json ./dist ./node_modules

      - name: Upload release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./package.zip

      - name: Run a one-line script
        run: echo Hello, world! 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo Node version ${{ inputs.nodeVersion }}
          echo package version: ${{ steps.pkg-version.outputs.version }} 
